### PR TITLE
I added my first work

### PR DESCRIPTION
**Pull request by korkmazhoruz**

### CODE REVIEW

**Comment by korkmazhoruz** [comment]
I am trying to follow instruction.

**Review by OzkokAhmet — COMMENTED** [review]
Cool code

**Comment by korkmazhoruz** [comment]
Test comment 9.45pm

**Comment by ada0734** [comment]
Looks good.

**Review by OzkokAhmet — CHANGES_REQUESTED** [review]
Put your full name please

**Comment by Jeyhun92** [comment]
I like your code

**Comment by tvasylyniuk** [comment]
found it

**Comment by Jeyhun92** [comment]
We can deploy this

**Comment by Jeyhun92** [comment]
Hello terminal Regina

**Comment by Antidetka** [comment]
hi Jehun

**Comment by EbruCetinBanse1** [comment]
Second try

**Comment by Jeyhun92** [comment]
Hi Regina. Queen of Terminal

**Pull request merged**
